name: ppparser
description: A Performance Port Parser that converts IP-port pairs to a JSON format.
version: 1.0.5
repository: https://www.github.com/tytydraco/ppparser

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  args: ^2.3.1

dev_dependencies:
  test: ^1.16.0
  very_good_analysis: ^3.0.1

executables:
  ppparser: ppparser
