name: ppparser
description: A Performance Port Parser that converts IP-port pairs to a JSON format.
version: 1.0.0
repository: https://www.github.com/tytydraco/ppparser

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  args: ^2.3.1
  logging: ^1.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
